/**
 * @license Highcharts JS v4.2.5 (2016-05-06)
 * Plugin for displaying a message when there is no data visible in chart.
 *
 * (c) 2010-2016 Highsoft AS
 * Author: Oystein Moseng
 *
 * License: www.highcharts.com/license
 */
(function(factory){if(typeof module==="object"&&module.exports){module.exports=factory}else{factory(Highcharts)}})(function(H){var seriesTypes=H.seriesTypes,chartPrototype=H.Chart.prototype,defaultOptions=H.getOptions(),extend=H.extend,each=H.each;extend(defaultOptions.lang,{noData:"No data to display"});defaultOptions.noData={position:{x:0,y:0,align:"center",verticalAlign:"middle"},attr:{},style:{fontWeight:"bold",fontSize:"12px",color:"#60606a"}};function hasDataPie(){return!!this.points.length}each(["pie","gauge","waterfall","bubble","treemap"],function(type){if(seriesTypes[type]){seriesTypes[type].prototype.hasData=hasDataPie}});H.Series.prototype.hasData=function(){return this.visible&&this.dataMax!==undefined&&this.dataMin!==undefined};chartPrototype.showNoData=function(str){var chart=this,options=chart.options,text=str||options.lang.noData,noDataOptions=options.noData;if(!chart.noDataLabel){chart.noDataLabel=chart.renderer.label(text,0,0,null,null,null,noDataOptions.useHTML,null,"no-data").attr(noDataOptions.attr).css(noDataOptions.style).add();chart.noDataLabel.align(extend(chart.noDataLabel.getBBox(),noDataOptions.position),false,"plotBox")}};chartPrototype.hideNoData=function(){var chart=this;if(chart.noDataLabel){chart.noDataLabel=chart.noDataLabel.destroy()}};chartPrototype.hasData=function(){var chart=this,series=chart.series,i=series.length;while(i--){if(series[i].hasData()&&!series[i].options.isInternal){return true}}return false};function handleNoData(){var chart=this;if(chart.hasData()){chart.hideNoData()}else{chart.showNoData()}}chartPrototype.callbacks.push(function(chart){H.addEvent(chart,"load",handleNoData);H.addEvent(chart,"redraw",handleNoData)})});